# Generated by Django 2.2.13 on 2022-04-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0019_auto_20190718_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travels', models.CharField(max_length=50)),
                ('departure_timeHours', models.CharField(max_length=2)),
                ('departure_timeMinutes', models.CharField(max_length=2)),
                ('departure_palce', models.CharField(max_length=50)),
                ('arrival_timeHours', models.CharField(max_length=2)),
                ('arrival_timeMinutes', models.CharField(max_length=2)),
                ('arrival_place', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=25)),
                ('fare', models.CharField(max_length=20)),
                ('seats_available', models.IntegerField()),
                ('ac_sleeper', models.CharField(max_length=20)),
                ('bus_num', models.CharField(default='AP04BN5444', max_length=15)),
                ('date', models.CharField(default='01/01/2021', max_length=10)),
                ('day', models.CharField(default='Friday', max_length=10)),
                ('one', models.CharField(default='#DDF4EC', max_length=10)),
                ('two', models.CharField(default='#DDF4EC', max_length=10)),
                ('three', models.CharField(default='#DDF4EC', max_length=10)),
                ('four', models.CharField(default='#DDF4EC', max_length=10)),
                ('five', models.CharField(default='#DDF4EC', max_length=10)),
                ('six', models.CharField(default='#DDF4EC', max_length=10)),
                ('seven', models.CharField(default='#DDF4EC', max_length=10)),
                ('eight', models.CharField(default='#DDF4EC', max_length=10)),
                ('nine', models.CharField(default='#DDF4EC', max_length=10)),
                ('ten', models.CharField(default='#DDF4EC', max_length=10)),
                ('elven', models.CharField(default='#DDF4EC', max_length=10)),
                ('twelve', models.CharField(default='#DDF4EC', max_length=10)),
                ('thirtn', models.CharField(default='#DDF4EC', max_length=10)),
                ('fouthn', models.CharField(default='#DDF4EC', max_length=10)),
                ('fivethn', models.CharField(default='#DDF4EC', max_length=10)),
                ('sixthn', models.CharField(default='#DDF4EC', max_length=10)),
            ],
            options={
                'db_table': 'buses_table',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=50)),
                ('departure_timeHours', models.CharField(max_length=2)),
                ('departure_timeMinutes', models.CharField(max_length=2)),
                ('departure_palce', models.CharField(max_length=50)),
                ('arrival_timeHours', models.CharField(max_length=2)),
                ('arrival_timeMinutes', models.CharField(max_length=2)),
                ('arrival_place', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=25)),
                ('fare', models.CharField(max_length=20)),
                ('seats_available', models.IntegerField()),
                ('date', models.CharField(default='01/04/2022', max_length=10)),
                ('day', models.CharField(default='Monday', max_length=10)),
            ],
            options={
                'db_table': 'flights_table',
            },
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('touristplces_covered', models.CharField(max_length=500)),
                ('hotel', models.CharField(max_length=150)),
                ('cost', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Tours',
            },
        ),
    ]
